# scan-project.ps1 - mechanical first-pass inventory of an unknown project.
#
# PowerShell twin of scan-project.sh. Emits a Markdown report to stdout:
# build system, toolchain, modules, deploy manifests, services & ports, env
# keys, entry points, existing docs. Gathers grep-able CANDIDATES with
# file:line - it does NOT decide meaning; the agent reading it extracts
# semantics. Safe on any repo; sections degrade to "none found".
# ASCII-only on purpose (Windows PowerShell 5.1 reads files as ANSI).
#
# Usage: powershell -NoProfile -File scan-project.ps1 [-Root <dir>]

param([string]$Root = ".")

$ErrorActionPreference = "SilentlyContinue"
$Root = (Resolve-Path $Root).Path
Set-Location $Root
$bt = [char]0x60   # backtick, for markdown code spans

$prune = @('.git','node_modules','target','build','dist','.idea','.gradle','vendor','.venv','__pycache__','.pytest_cache','.mypy_cache','.ruff_cache','.tox','htmlcov')

function Get-Files([string[]]$Patterns) {
  Get-ChildItem -Path $Root -Recurse -File -Include $Patterns 2>$null | Where-Object {
    $p = $_.FullName
    -not ($prune | Where-Object { $p -match [regex]::Escape([IO.Path]::DirectorySeparatorChar + $_ + [IO.Path]::DirectorySeparatorChar) })
  }
}
function Rel([string]$Path) { $Path.Substring($Root.Length).TrimStart('\','/') -replace '\\','/' }
function Code([string]$s) { "$bt$s$bt" }
function Section([string]$t) { "`n## $t`n" }
function GrepIn($files, [string]$pat, [int]$max = 60) {
  $out = @()
  foreach ($f in $files) {
    Select-String -Path $f.FullName -Pattern $pat -AllMatches 2>$null | ForEach-Object {
      $out += ("    " + (Rel $_.Path) + ":" + $_.LineNumber + ":" + $_.Line.Trim())
    }
    if ($out.Count -ge $max) { break }
  }
  $out | Select-Object -First $max
}

"# Project scan - $Root"
"_generated by scan-project - candidates only; verify semantics by reading the files_"

# ---- build system
Section "Build system & manifests"
$bf = Get-Files @('pom.xml','build.gradle','build.gradle.kts','settings.gradle','settings.gradle.kts','package.json','pnpm-workspace.yaml','go.mod','Cargo.toml','pyproject.toml','requirements.txt','Makefile','CMakeLists.txt','composer.json','Gemfile') | Sort-Object FullName
if ($bf) { $bf | ForEach-Object { "- " + (Code (Rel $_.FullName)) } } else { "_none found_" }

# ---- modules
Section "Modules / sub-projects"
$found = $false
foreach ($p in (Get-Files @('pom.xml'))) {
  $mods = Select-String -Path $p.FullName -Pattern '<module>([^<]+)</module>' -AllMatches |
          ForEach-Object { $_.Matches } | ForEach-Object { $_.Groups[1].Value }
  if ($mods) { "- from " + (Code (Rel $p.FullName)) + ":"; $mods | ForEach-Object { "    - $_" }; $found = $true }
}
foreach ($s in (Get-Files @('settings.gradle','settings.gradle.kts'))) {
  $inc = Select-String -Path $s.FullName -Pattern '^\s*include[ (]'
  if ($inc) { "- from " + (Code (Rel $s.FullName)) + ":"; $inc | ForEach-Object { "    " + $_.Line.Trim() }; $found = $true }
}
foreach ($pj in (Get-Files @('package.json'))) {
  if (Select-String -Path $pj.FullName -Pattern '"workspaces"' -Quiet) { "- npm/yarn workspaces in " + (Code (Rel $pj.FullName)); $found = $true }
}
if (-not $found) { "_no multi-module layout detected - likely a single module_" }

# ---- toolchain
Section "Toolchain / required versions"
$found = $false
foreach ($f in @('.java-version','.sdkmanrc','.nvmrc','.node-version','.tool-versions','.ruby-version','.python-version','runtime.txt','.mise.toml')) {
  foreach ($m in (Get-Files @($f))) { "- " + (Code (Rel $m.FullName)) + ": " + ((Get-Content $m.FullName -TotalCount 3) -join ' '); $found = $true }
}
$jv = GrepIn (Get-Files @('pom.xml','build.gradle','build.gradle.kts')) 'maven\.compiler|<release>|<java\.version>|sourceCompatibility|targetCompatibility|languageVersion' 20
if ($jv) { "- version pins in build files:"; $jv; $found = $true }
$df = GrepIn (Get-Files @('Dockerfile','Dockerfile.*')) '^FROM ' 20
if ($df) { "- base images (FROM):"; $df; $found = $true }
if (Test-Path "$Root/.github") {
  $ci = Select-String -Path "$Root/.github/*","$Root/.github/workflows/*" -Pattern 'java-version|node-version|go-version|python-version|distribution:' 2>$null |
        Select-Object -First 20 | ForEach-Object { "    " + (Rel $_.Path) + ":" + $_.LineNumber + ":" + $_.Line.Trim() }
  if ($ci) { "- CI version pins:"; $ci; $found = $true }
}
if (-not $found) { "_none found_" }

# ---- deploy manifests
Section "Deploy manifests (k8s / compose / helm / docker)"
$found = $false
$cf = Get-Files @('docker-compose*.yml','docker-compose*.yaml','compose.yml','compose.yaml')
if ($cf) { $cf | ForEach-Object { "- compose: " + (Code (Rel $_.FullName)) }; $found = $true }
$hc = Get-Files @('Chart.yaml'); if ($hc) { $hc | ForEach-Object { "- helm: " + (Code (Rel $_.FullName)) }; $found = $true }
$dk = Get-Files @('Dockerfile','Dockerfile.*'); if ($dk) { $dk | ForEach-Object { "- dockerfile: " + (Code (Rel $_.FullName)) }; $found = $true }
$k8s = Get-Files @('*.yml','*.yaml') | Where-Object { Select-String -Path $_.FullName -Pattern '^kind:\s*(Service|Deployment|StatefulSet|Ingress|ConfigMap|Secret|CronJob|Job|DaemonSet)\b' -Quiet } | Sort-Object FullName
if ($k8s) { $k8s | ForEach-Object { "- k8s: " + (Code (Rel $_.FullName)) }; $found = $true }
if (-not $found) { "_none found_" }

# ---- services & ports
Section "Service & port candidates"
"_raw hits - map each to a service by reading the file_`n"
$ph = GrepIn (Get-Files @('*.yml','*.yaml','Dockerfile','Dockerfile.*','*.properties','*.conf')) '(containerPort|targetPort|nodePort|EXPOSE |server\.port|["'' ]port["'' ]?:\s*[0-9]|- *"?[0-9]{2,5}:[0-9]{2,5})' 60
if ($ph) { '```'; $ph | ForEach-Object { $_.Trim() }; '```' } else { "_none found_" }

# ---- env keys
Section "Environment variable candidates"
"_dedup the names; decide which are secrets (never print values)_`n"
$envfiles = Get-Files @('.env.example','.env.sample','.env.template','*.env.example','.env.dist')
if ($envfiles) { "- template files:"; $envfiles | ForEach-Object { "    - " + (Code (Rel $_.FullName)) } }
$srcs = Get-Files @('*.java','*.kt','*.ts','*.js','*.go','*.py','*.yml','*.yaml','*.properties')
$names = @{}
foreach ($f in $srcs) {
  Select-String -Path $f.FullName -Pattern '(System\.getenv\("|process\.env\.|os\.environ\[?["'']?|getenv\("|\$\{|@Value\("\$\{)([A-Z][A-Z0-9_]{2,})' -AllMatches |
    ForEach-Object { $_.Matches } | ForEach-Object { if ($_.Groups[2].Value) { $names[$_.Groups[2].Value] = $true } }
}
if ($names.Count) { "- referenced names:"; $names.Keys | Sort-Object | Select-Object -First 80 | ForEach-Object { "    - $_" } } else { "- referenced names: _none found_" }

# ---- secrets
Section "Sensitive files (paths only - NEVER opened)"
"_if any appear, a real secret may be committed; do NOT read them, warn the user, and for a public repo run scrub-identity_`n"
$sec = Get-Files @('.env','.env.local','.env.*.local','*.pem','*.key','id_rsa','id_rsa.*','*.p12','*.pfx','*.keystore','*.jks','credentials.json','service-account*.json','.netrc','.pypirc') |
       Where-Object { $_.Name -notmatch '\.env\.(example|sample|template|dist)$' } | Sort-Object FullName
if ($sec) { $sec | ForEach-Object { "- (!) " + (Code (Rel $_.FullName)) } } else { "_none found_" }

# ---- entry points
Section "Entry points / run commands"
$found = $false
$mn = Get-Files @('*.java','*.kt','*.py','*.go') | Where-Object { Select-String -Path $_.FullName -Pattern 'public static void main|if __name__ == .__main__.|func main\(\)' -Quiet } | Select-Object -First 25
if ($mn) { "- main() / entry in:"; $mn | ForEach-Object { "    - " + (Rel $_.FullName) }; $found = $true }
$tr = Get-Files @('Procfile','Makefile','Taskfile.yml','justfile')
if ($tr) { $tr | ForEach-Object { "- task runner: " + (Code (Rel $_.FullName)) }; $found = $true }
if (-not $found) { "_none found_" }

# ---- existing docs
Section "Existing docs"
$docs = Get-Files @('README*','AGENTS.md','CONTRIBUTING*','RUN.md') | Sort-Object FullName
if ($docs) { $docs | ForEach-Object { "- " + (Code (Rel $_.FullName)) } } else { "_none found_" }

"`n---`n_scan complete_"
