#!/bin/sh
# scan-project.sh — mechanical first-pass inventory of an unknown project.
#
# Emits a Markdown report to stdout: build system, toolchain hints, modules,
# deploy manifests, services & ports, env keys, entry points, existing docs.
# It gathers grep-able CANDIDATES with file:line — it does NOT decide meaning.
# The agent reading the output does the semantic extraction (which port belongs
# to which service, which env key is a secret). Safe on any repo; every section
# degrades to "none found" when the inputs are absent. Single-pass greps keep it
# fast even on large monorepos.
#
# Usage: scan-project.sh [TARGET_DIR]   (default: current directory)

set -u
ROOT="${1:-.}"
cd "$ROOT" 2>/dev/null || { echo "cannot cd into $ROOT" >&2; exit 2; }
ROOT_ABS="$(pwd)"

# Never source-of-truth — excluded from every recursive grep and find.
XD='--exclude-dir=.git --exclude-dir=node_modules --exclude-dir=target --exclude-dir=build --exclude-dir=dist --exclude-dir=.idea --exclude-dir=.gradle --exclude-dir=vendor --exclude-dir=.venv --exclude-dir=__pycache__ --exclude-dir=.pytest_cache --exclude-dir=.mypy_cache --exclude-dir=.ruff_cache --exclude-dir=.tox --exclude-dir=htmlcov'
PRUNE='-name .git -o -name node_modules -o -name target -o -name build -o -name dist -o -name .idea -o -name .gradle -o -name vendor -o -name .venv -o -name __pycache__ -o -name .pytest_cache -o -name .mypy_cache -o -name .ruff_cache -o -name .tox -o -name htmlcov'

# find files by -name expression, honouring the prune list (filenames only — cheap).
ff() { find . \( $PRUNE \) -prune -o -type f \( $@ \) -print 2>/dev/null; }

section() { printf '\n## %s\n\n' "$1"; }
none() { printf '_none found_\n'; }

printf '# Project scan — %s\n' "$ROOT_ABS"
printf '_generated by scan-project — candidates only; verify semantics by reading the files_\n'

# ---------------------------------------------------------------- build system
section "Build system & manifests"
bf=$(ff "-name pom.xml -o -name build.gradle -o -name build.gradle.kts -o -name settings.gradle -o -name settings.gradle.kts -o -name package.json -o -name pnpm-workspace.yaml -o -name go.mod -o -name Cargo.toml -o -name pyproject.toml -o -name requirements.txt -o -name Makefile -o -name CMakeLists.txt -o -name composer.json -o -name Gemfile" | sed 's:^\./::' | sort)
if [ -n "$bf" ]; then printf '%s\n' "$bf" | sed 's/^/- `/; s/$/`/'; else none; fi

# ---------------------------------------------------------------- modules
section "Modules / sub-projects"
found=0
for p in $(ff "-name pom.xml"); do
  mods=$(grep -oE '<module>[^<]+</module>' "$p" 2>/dev/null | sed -E 's:</?module>::g')
  if [ -n "$mods" ]; then
    printf -- '- from `%s`:\n' "${p#./}"
    for mm in $mods; do printf -- '    - %s\n' "$mm"; done
    found=1
  fi
done
for s in $(ff "-name settings.gradle -o -name settings.gradle.kts"); do
  inc=$(grep -nE "^[[:space:]]*include[ (]" "$s" 2>/dev/null)
  [ -n "$inc" ] && { printf -- '- from `%s`:\n' "${s#./}"; printf '%s\n' "$inc" | sed 's/^/    /'; found=1; }
done
grep -rlE '"workspaces"' --include=package.json $XD . 2>/dev/null | while IFS= read -r pj; do
  printf -- '- npm/yarn workspaces in `%s`\n' "${pj#./}"
done | grep . && found=1
[ "$found" -eq 0 ] && printf '_no multi-module layout detected — likely a single module_\n'

# ---------------------------------------------------------------- toolchain
section "Toolchain / required versions"
found=0
for f in .java-version .sdkmanrc .nvmrc .node-version .tool-versions .ruby-version .python-version runtime.txt .mise.toml; do
  for m in $(ff "-name $f"); do
    printf -- '- `%s`: %s\n' "${m#./}" "$(head -c 200 "$m" | tr '\n' ' ')"; found=1
  done
done
jv=$(grep -rInE 'maven.compiler|<release>|<java.version>|sourceCompatibility|targetCompatibility|languageVersion' --include=pom.xml --include=build.gradle --include=build.gradle.kts $XD . 2>/dev/null | head -20)
[ -n "$jv" ] && { printf -- '- version pins in build files:\n'; printf '%s\n' "$jv" | sed 's/^/    /'; found=1; }
df=$(grep -rInE '^FROM ' --include=Dockerfile --include='Dockerfile.*' $XD . 2>/dev/null | head -20)
[ -n "$df" ] && { printf -- '- base images (`FROM`):\n'; printf '%s\n' "$df" | sed 's/^/    /'; found=1; }
ci=$(grep -rInE 'java-version|node-version|go-version|python-version|distribution:' $XD ./.github 2>/dev/null | head -20)
[ -n "$ci" ] && { printf -- '- CI version pins:\n'; printf '%s\n' "$ci" | sed 's/^/    /'; found=1; }
[ "$found" -eq 0 ] && none

# ---------------------------------------------------------------- deploy manifests
section "Deploy manifests (k8s / compose / helm / docker)"
found=0
cf=$(ff "-iname docker-compose*.yml -o -iname docker-compose*.yaml -o -iname compose.yml -o -iname compose.yaml" | sed 's:^\./::')
[ -n "$cf" ] && { printf '%s\n' "$cf" | sed 's/^/- compose: `/; s/$/`/'; found=1; }
hc=$(ff "-iname Chart.yaml" | sed 's:^\./::')
[ -n "$hc" ] && { printf '%s\n' "$hc" | sed 's/^/- helm: `/; s/$/`/'; found=1; }
dk=$(ff "-iname Dockerfile -o -iname Dockerfile.*" | sed 's:^\./::')
[ -n "$dk" ] && { printf '%s\n' "$dk" | sed 's/^/- dockerfile: `/; s/$/`/'; found=1; }
# k8s manifests: yaml declaring a workload/networking kind — one grep pass for the file list
k8s=$(grep -rlE '^kind:[[:space:]]*(Service|Deployment|StatefulSet|Ingress|ConfigMap|Secret|CronJob|Job|DaemonSet)\b' --include=*.yml --include=*.yaml $XD . 2>/dev/null | sed 's:^\./::' | sort)
[ -n "$k8s" ] && { printf '%s\n' "$k8s" | sed 's/^/- k8s: `/; s/$/`/'; found=1; }
[ "$found" -eq 0 ] && none

# ---------------------------------------------------------------- services & ports
section "Service & port candidates"
printf '_raw hits — map each to a service by reading the file_\n\n'
ph=$(grep -rInE '(containerPort|targetPort|nodePort|EXPOSE |server\.port|["'\'' ]port["'\'' ]?:[[:space:]]*[0-9]|- *"?[0-9]{2,5}:[0-9]{2,5})' \
      --include=*.yml --include=*.yaml --include=Dockerfile --include='Dockerfile.*' --include=*.properties --include=*.conf $XD . 2>/dev/null | head -60)
if [ -n "$ph" ]; then printf '```\n%s\n```\n' "$ph"; else none; fi

# ---------------------------------------------------------------- env keys
section "Environment variable candidates"
printf '_dedup the names; decide which are secrets (never print values)_\n\n'
envfiles=$(ff "-name .env.example -o -name .env.sample -o -name .env.template -o -name *.env.example -o -name .env.dist" | sed 's:^\./::')
[ -n "$envfiles" ] && { printf -- '- template files:\n'; printf '%s\n' "$envfiles" | sed 's/^/    - `/; s/$/`/'; }
eh=$(grep -rhoE '(System\.getenv\("[A-Z0-9_]+|process\.env\.[A-Z0-9_]+|os\.environ\[?["'\'']?[A-Z0-9_]+|getenv\("[A-Z0-9_]+|\$\{[A-Z0-9_]+\}|@Value\("\$\{[A-Za-z0-9_.]+)' \
      --include=*.java --include=*.kt --include=*.ts --include=*.js --include=*.go --include=*.py --include=*.yml --include=*.yaml --include=*.properties $XD . 2>/dev/null \
      | grep -oE '[A-Z][A-Z0-9_]{2,}' | sort -u | head -80)
if [ -n "$eh" ]; then printf -- '- referenced names:\n'; printf '%s\n' "$eh" | sed 's/^/    - /'; else printf -- '- referenced names: '; none; fi

# ---------------------------------------------------------------- entry points
section "Entry points / run commands"
found=0
mn=$(grep -rlE 'public static void main|if __name__ == .__main__.|func main\(\)' --include=*.java --include=*.kt --include=*.py --include=*.go $XD . 2>/dev/null | sed 's:^\./::' | head -25)
[ -n "$mn" ] && { printf -- '- main() / entry in:\n'; printf '%s\n' "$mn" | sed 's/^/    - /'; found=1; }
tr=$(ff "-name Procfile -o -name Makefile -o -name Taskfile.yml -o -name justfile" | sed 's:^\./::')
[ -n "$tr" ] && { printf '%s\n' "$tr" | sed 's/^/- task runner: `/; s/$/`/'; found=1; }
[ "$found" -eq 0 ] && none

# ---------------------------------------------------------------- existing docs
section "Existing docs"
docs=$(ff "-iname README* -o -iname AGENTS.md -o -iname CONTRIBUTING* -o -iname RUN.md" | sed 's:^\./::' | sort)
if [ -n "$docs" ]; then printf '%s\n' "$docs" | sed 's/^/- `/; s/$/`/'; else none; fi

printf '\n---\n_scan complete_\n'
