# gen-port-forward.ps1 - emit a runnable kubectl port-forward launcher (Windows).
#
# PowerShell twin of gen-port-forward.sh. GENERATES a script to stdout; it does
# not forward anything itself. Review, save as
# docs/onboarding/scripts/port-forward.ps1 in the target repo, then run that.
# ASCII-only on purpose (Windows PowerShell 5.1 reads files as ANSI).
#
# Usage:
#   powershell -NoProfile -File gen-port-forward.ps1 -Namespace dev -Maps "postgres:5432:5432,redis:6379"
# -Maps is ONE comma-separated string of  service:local[:remote]  mappings
# (a single string so it survives `powershell -File`, which does not split
# commas into an array). remote defaults to local when omitted.

param(
  [Parameter(Mandatory=$true)][string]$Namespace,
  [Parameter(Mandatory=$true)][string]$Maps
)

$lines = @()
$lines += "# port-forward.ps1 - GENERATED by agent-skills/run-guide/gen-port-forward.ps1"
$lines += "# Opens kubectl port-forwards to backing services so the app can reach them on"
$lines += "# localhost. Close the window (or Ctrl-C) to tear them down. Needs a kube-context."
$lines += '$ErrorActionPreference = "Stop"'
$lines += ('$NS = "' + $Namespace + '"')
$lines += '$jobs = @()'
$lines += "try {"

foreach ($m in ($Maps.Split(",") | Where-Object { $_ -ne "" })) {
  $parts = $m.Split(":")
  if ($parts.Count -lt 2 -or $parts[0] -eq "" -or $parts[1] -eq "") { Write-Error "bad mapping: $m"; exit 2 }
  $svc = $parts[0]; $lp = $parts[1]
  $rp = if ($parts.Count -ge 3 -and $parts[2] -ne "") { $parts[2] } else { $lp }
  $lines += ('  Write-Host "forward ' + $svc + '  localhost:' + $lp + ' -> svc/' + $svc + ':' + $rp + '"')
  $lines += ('  $jobs += Start-Job { kubectl -n ''' + $Namespace + ''' port-forward ''svc/' + $svc + ''' ''' + $lp + ':' + $rp + ''' }')
}

$lines += '  Write-Host "all forwards up (namespace: $NS). Close this window to stop."'
$lines += '  Wait-Job $jobs | Out-Null'
$lines += "}"
$lines += "finally {"
$lines += '  Write-Host "stopping port-forwards..."'
$lines += '  $jobs | Stop-Job -PassThru | Remove-Job -Force'
$lines += "}"

$lines -join "`r`n"
