#!/bin/sh
# gen-port-forward.sh — emit a runnable kubectl port-forward launcher.
#
# It GENERATES a script (to stdout); it does not forward anything itself. Review
# the output, save it as docs/onboarding/scripts/port-forward.sh in the target
# repo, then run that — so the port-forward route becomes a checked-in artifact,
# not a one-off command lost after the session.
#
# Usage:
#   gen-port-forward.sh <namespace> <svc:local:remote> [<svc:local:remote> ...]
# Example:
#   gen-port-forward.sh dev postgres:5432:5432 redis:6379:6379 llm-gateway:8081:8080
#
# Each mapping is  service-name : local-port : remote-port  (remote defaults to
# local if omitted). Forwards run in the background; Ctrl-C stops all of them.

set -u
[ $# -lt 2 ] && { echo "usage: $0 <namespace> <svc:local[:remote]> ..." >&2; exit 2; }
NS="$1"; shift

cat <<'HEADER'
#!/bin/sh
# port-forward.sh — GENERATED by agent-skills/run-guide/gen-port-forward.sh
# Opens kubectl port-forwards to backing services so the app can reach them on
# localhost. Ctrl-C tears them all down. Requires a working kube-context.
set -u
pids=""
cleanup() { echo; echo "stopping port-forwards..."; kill $pids 2>/dev/null; exit 0; }
trap cleanup INT TERM
HEADER
printf 'NS=%s\n\n' "$NS"

for map in "$@"; do
  svc=$(printf '%s' "$map" | cut -d: -f1)
  lp=$(printf '%s' "$map" | cut -d: -f2)
  rp=$(printf '%s' "$map" | cut -d: -f3)
  [ -z "$rp" ] && rp="$lp"
  [ -z "$svc" ] || [ -z "$lp" ] && { echo "bad mapping: $map" >&2; exit 2; }
  printf 'echo "forward %s  localhost:%s -> svc/%s:%s"\n' "$svc" "$lp" "$svc" "$rp"
  printf 'kubectl -n "$NS" port-forward "svc/%s" %s:%s >/dev/null 2>&1 &\n' "$svc" "$lp" "$rp"
  printf 'pids="$pids $!"\n\n'
done

cat <<'FOOTER'
echo "all forwards up (namespace: $NS). Ctrl-C to stop."
wait
FOOTER
